# Generated by Django 2.2.13 on 2022-04-20 04:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentOfMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(default='', editable=False, max_length=300)),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Curated by')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='danam-cms/', verbose_name='Thumbnail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='danam-cms/', verbose_name='Primary Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
            ],
            options={
                'verbose_name': 'monument-of-month',
                'verbose_name_plural': 'monument-of-months',
                'db_table': 'monument_of_month',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('created_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'db_table': 'danam_news',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PdfUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Publisher')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Publication Date')),
                ('docfile', models.FileField(upload_to='danam-cms/')),
            ],
            options={
                'db_table': 'pdf_uploader',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preflabel', models.CharField(max_length=50)),
                ('altlabel', models.CharField(max_length=50)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploadedfiles/news_img/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='danam.News')),
            ],
            options={
                'db_table': 'news_images',
            },
        ),
        migrations.CreateModel(
            name='Glossimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altimage', models.CharField(max_length=300)),
                ('tnimage', models.CharField(max_length=300)),
                ('heidicon', models.CharField(max_length=200)),
                ('imgmain', models.BooleanField()),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danam.Terms')),
            ],
        ),
    ]
